name: Azure Deployment

on: 
  push:
    branches:
      - main
    paths:
      - infrastructure/**
  pull_request:
    paths:
      - infrastructure/**
  workflow_dispatch: # Manual trigger

permissions:
  contents: read
  id-token: write

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps: 
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - uses: Azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ secrets.RESOURCE_GROUP_NAME }} --location ${{ secrets.RESOURCE_GROUP_LOCATION }}
            echo "Azure resource group created successfully."
      
      - name: Deploy
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
          template: ./infrastructure/main.bicep
